Fruits = ['orange', 'cherry', 'apple']
print(Fruits)
Fruits.append('banana')
print(Fruits)
Fruits.insert(1, 'apple')
print(Fruits)
print(Fruits[0])
Fruits.remove('apple')
print(Fruits)
Fruits.pop(1)
print(Fruits)
Fruits.pop()
print(Fruits)
Days = ("Monday", "Tuesday", "Sunday")
print(Days)
print(len(Fruits))
